CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# Enable Display Support
CONFIG_ZMK_DISPLAY=y

# Use the custom Prospector widget (Optional but recommended)
# This usually requires the prospector module to be active
CONFIG_CHARACTER_FRAMEBUFFER=y